version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7.4

  celery-flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      FLOWER_PORT: 5555

  celery-worker:
    deploy:
      replicas: 1
    image: sgonzalezmo/kafka-celery-worker:latest
    build:
      context: https://github.com/sgonzalezmo/kafka-celery-worker.git
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC: test
      KAFKA_CONSUMER_GROUP: kafka-celery-worker-consumer-group
      KAFKA_CONSUMER_TIMEOUT: 1000

  celery-beat:
    image: sgonzalezmo/kafka-celery-beat:latest
    build:
      context: https://github.com/sgonzalezmo/kafka-celery-beat.git
    depends_on:
      - redis
      - kafka
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379